"""Write a small mkdocs project around a trace.

The page from ``hook-atlas draw`` is enough to look at something once. This is
for the other case: a page you publish, that someone else finds, that needs a
title and navigation and somewhere to say what it is.

It is deliberately thin. The diagrams and the hook table come from the same
renderer the standalone page uses, so there is one implementation to keep
right; what is added here is the project around it.
"""

from __future__ import annotations

from pathlib import Path

from . import config

MKDOCS_YML = """\
site_name: {name} hook flow
site_description: What the hooks did, in order, captured from a real run.

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: {{ icon: material/weather-night, name: Dark }}
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: {{ icon: material/weather-sunny, name: Light }}
  features:
    - content.code.copy
    - navigation.instant

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html          # the hook table is HTML, and needs to stay HTML
  - pymdownx.highlight
  - pymdownx.snippets: {{ base_path: ["docs"] }}
  - pymdownx.superfences
"""

BUILD_SCRIPT = """\
#!/usr/bin/env bash
# Trace, draw, publish. Re-run after any change to the suite or the config.
set -euo pipefail

# Your project, not this directory: the site lives inside the repository it
# documents, and the command has to run where the suite is.
PROJECT_ROOT="${{PROJECT_ROOT:-..}}"
SITE="$(cd "$(dirname "$0")" && pwd)"

# 1. Record a run. Everything after `--` is your command, untouched.
#
#    `|| true` on purpose: hook-atlas returns your command's exit code, and a
#    suite with a failing test is exactly when you want the picture. Without
#    this, `set -e` would stop here and you would get nothing.
( cd "$PROJECT_ROOT" && hook-atlas trace -o "$SITE/trace.json" -- {command} ) || true

# 2. Render it. --config is what separates the phases, links the hooks and
#    names the plugins as yours or the application's; without it you get one
#    flow and no links.
hook-atlas draw "$SITE/trace.json" --config "$SITE/atlas.toml" -o "$SITE/docs/flow.md"

# 3. The page mkdocs renders. Edit the prose; the flow is included.
cat > "$SITE/docs/index.md" <<'PAGE'
# {name} hook flow

What the hooks actually did, captured from a real run with
[hook-atlas](https://github.com/zy1o/hook-atlas).

--8<-- "flow.md"
PAGE

echo "built docs/index.md - run 'mkdocs serve' to look at it"
"""

README = """\
# {name} hook flow

Generated by [hook-atlas](https://zy1o.github.io/hook-atlas/).

```bash
./build.sh        # trace, draw, assemble
mkdocs serve      # look at it
mkdocs gh-deploy  # publish to GitHub Pages
```

`atlas.toml` describes the application: which phases the run is divided into,
where its hook documentation lives, and which modules count as its own. Edit it
and re-run `./build.sh` - no re-tracing needed unless the suite changed.
"""

GITIGNORE = "site/\ntrace.json\ndocs/flow.html\n"


def init_site(directory: Path, name: str, command: str, example: str = "pytest") -> list[Path]:
    """Write the project. Returns what it wrote, in the order worth reading."""
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "docs").mkdir(exist_ok=True)

    written = []
    files = {
        "atlas.toml": config.example(example).read_text(),
        "mkdocs.yml": MKDOCS_YML.format(name=name),
        "build.sh": BUILD_SCRIPT.format(name=name, command=command),
        "README.md": README.format(name=name),
        ".gitignore": GITIGNORE,
    }
    for filename, content in files.items():
        path = directory / filename
        path.write_text(content)
        written.append(path)

    (directory / "build.sh").chmod(0o755)
    return written
